zuul:
  sensitive-headers:
  routes:
    auth:
      path: /auth/**
      serviceId: user
      # 默认为 true，会去掉 /auth 前缀进行转发，此处保留前缀转发
      strip-prefix: false
    user:
      path: /user/**
      serviceId: user
      strip-prefix: false
    group:
      path: /group/**
      serviceId: group
      strip-prefix: false
    file:
      path: /file/**
      serviceId: file
      strip-prefix: false
    message:
      path: /message/**
      serviceId: message
      strip-prefix: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

spring:
  application:
    name: api-gateway

  redis:
    host: 127.0.0.1
    port: 6379
    #password: myredis
    timeout: 3000
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 30
        #最大空闲时间
        max-idle: 10

  session:
    store-type: redis
    timeout: 300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
