spring:
  application:
    name: api-gateway

  redis:
    host: 127.0.0.1
    port: 6379
    #password: myredis
    timeout: 3000
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 30
        #最大空闲时间
        max-idle: 10

  session:
    store-type: redis
    timeout: 300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080