server:
  port: 9050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# apollo 配置中心
app:
  id: file
apollo:
  bootstrap:
    enabled: true
    # namespace, 中间以逗号间隔
    namespaces: application, my_project.chat-datasource, my_project.chat-redis, my_project.chat-commom-config, my_project.chat-mybatis, my_project.chat-kafka
  #自定义缓存路径
  cacheDir: apollo-cacheDir/account-service
  #集群
  cluster: DEFAULT
  # Apollo Meta Server
  meta: http://localhost:8080

spring:
  application:
    name: file

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: fan
#    password: Fmy1054.
#    url: jdbc:mysql://106.14.120.166:3400/chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 10
#      max-active: 500
#      min-idle: 10
#      max-wait: 60000

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: true

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    # password: myredis
#    timeout: 3000
#    database: 0
#    jedis:
#      pool:
#        #最大连接数
#        max-active: 30
#        #最大空闲时间
#        max-idle: 10

#  session:
#    store-type: redis
#    timeout: 300

#  servlet:
#    multipart:
#      max-file-size: 500MB
#      max-request-size: 2048MB

#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#      bindings:
#        fileDeleteInput:
#          destination: fileDelete
#          contentType: application/json
#          group: ${spring.application.name}


#mybatis:
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: org.freud.file.entity, org.freud.file.common
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#
#pagehelper:
#  reasonable: true
#  support-methods-arguments: true
#  auto-dialect: true

