spring:
  application:
    name: user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fan
    password: Fmy1054.
    url: jdbc:mysql://106.14.120.166:3400/chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 500
      min-idle: 10
      max-wait: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

  redis:
    host: 127.0.0.1
    port: 6379
    #password: myredis
    timeout: 3000
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 30
        #最大空闲时间
        max-idle: 10

  session:
    store-type: redis
    timeout: 300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: org.freud.user.entity, org.freud.user.common
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  support-methods-arguments: true
  auto-dialect: true

server:
  port: 9020