spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fan
    password: Fmy1054.
    url: jdbc:mysql://106.14.120.166:3400/chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 500
      min-idle: 1
      max-wait: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.sandau.chat.entity, edu.sandau.chat.vo, edu.sandau.chat.netty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  support-methods-arguments: true
  auto-dialect: true

server:
  port: 9010